name: build.yml
on:
  push:
    branches: [ '**' ]

jobs:
  setup:
    runs-on: ubuntu-latest

  tsc-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Run build step
        run: npm run build

  docker-build:
    runs-on: ubuntu-latest
    needs: tsc-build
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup runner
        uses: pguyot/arm-runner-action@v2

      - name: Build the Docker Image
        run: |
          uname -m
          docker build . --platform linux/arm64 --tag archi-back:latest

      - name: Save archive
        if: github.ref == 'refs/heads/ci/cd'
        run: |
          docker save archi-back:latest > archi-back.tar

      - name: Upload Docker image artifact
        if: github.ref == 'refs/heads/ci/cd'
        uses: actions/upload-artifact@v4
        with:
          name: archi-back-image
          path: archi-back.tar