name: CI/CD pipeline

on:
  push:
    branches: [ '**' ]
  pull_request:
    branches: [ '**' ]


jobs:
  tsc-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Run build step
        run: npm run build

  docker-build:
    runs-on: ubuntu-latest
    needs: tsc-build
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup runner
        uses: pguyot/arm-runner-action@v2

      - name: Build the Docker Image
        run: |
          uname -m
          docker build . --platform linux/arm64 --tag archi-back:latest --progress=plain 

      - name: Save archive
        if: github.ref == 'refs/heads/prod'
        run: |
          docker save archi-back:latest > archi-back.tar

      - name: Upload Docker image artifact
        if: github.ref == 'refs/heads/prod'
        uses: actions/upload-artifact@v4
        with:
          name: archi-back-image-${{ github.run_id }}
          path: archi-back.tar
          overwrite: true

  deploy:
    if: github.ref == 'refs/heads/prod'
    runs-on: ubuntu-latest
    needs: docker-build

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Download Docker Image Artifact
        uses: actions/download-artifact@v4
        with:
          name: archi-back-image-${{ github.run_id }}
          path: ./

      - name: Copy Image to Remote Server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.RSPB_HOST }}
          username: ${{ secrets.RSPB_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          passphrase: ${{ secrets.SSH_PASSPHRASE }}
          source: ./archi-back.tar
          target: /tmp
          port: ${{ secrets.RSPB_PORT }}

      - name: Load and Run the Docker Image on Server
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.RSPB_HOST }}
          username: ${{ secrets.RSPB_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          passphrase: ${{ secrets.SSH_PASSPHRASE }}
          port: ${{ secrets.RSPB_PORT }}
          script: |
            export RSPB_USER=${{ secrets.RSPB_USER }}
            docker ps -a --filter "name=archi-back" -q | grep -q . && docker rm -f archi-back && docker rmi -f archi-back:latest || echo "Container archi-back doesn't exist"
            docker load < /tmp/archi-back.tar
            docker run -d --name archi-back --env-file /home/$RSPB_USER/.env -p 3000:3000 archi-back:latest
            while ! docker inspect -f '{{.State.Running}}' archi-back; do echo "Waiting for container to be ready..."; sleep 5; done
#